// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzugawjaqfolfeslequh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6dWdhd2phcWZvbGZlc2xlcXVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMjA1MjEsImV4cCI6MjA2NTU5NjUyMX0.0UHQ6blcva14lfSIYOZUa1fd237Q6NUOWKkrlZgMVZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);